version: '3'
services:
  vet_app:
    build: .
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: vet2024
      MYSQL_DATABASE: vet_app